config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :gists, only: :create

  resource :feedback, only: %i[new create]
  resources :badges, only: :index
  resources :received_badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passeges/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, counter_cache: true

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :nullify, foreign_key: :current_question_id

  validates :body, presence: true

  def number
    test.questions.order(:id).where('id <= ?', id).count
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :find_test, only: %i[create new]
  before_action :find, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_test_path(@test)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test)
  end

  private

  def find
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test, only: %i[create new]
  before_action :find, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show; end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to test_path(@test)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to test_path(@question.test)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to test_path(@question.test)
  end

  private

  def find
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end

  def rescue_with_question_not_found
    render plain: 'Question was not found'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.test.title
    if question.new_record?
      t('admin.questions.create.header', title: title)
    else
      t('admin.questions.edit.header', title: title)
    end
  end
end

app/views/questions/_form.html.erb
<h1><%= question_header(@question) %></h1>

<%= form_with model: [@test, @question], local: true do |form| %>
  <%= render 'shared/errors', resource: @question %>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, id: :question_body, rows: 7, cols: 60 %>
  </p>
  
  
  <p><%= form.submit %></p>
<% end %>

app/views/questions/_index.html.erb
<h3>Questions:</h3>
<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'questions/question', collection: @questions %>
  </tbody> 
</table>
<p>
  <%= link_to 'New question', new_test_question_path(@test, @question) %>
</p>
<p>
<%= link_to 'Back to tests', admin_tests_path%>
</p>

app/views/questions/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<h2>Answers</h2>

<%= link_to 'New answer', new_question_answer_path(@question) %>

<ol>
  <%= render @question.answers %>
</ol>
<p>
<%= link_to 'Edit', edit_question_path(@question)%> | 
<%= link_to 'Back', admin_test_path(@question.test)%>
</p>