config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :gists, only: :create

  resource :feedback, only: %i[new create]
  resources :badges, only: :index
  resources :received_badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passeges/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/badge.rb
class Badge < ApplicationRecord

  has_many :received_badge
  has_many :users, through: :received_badge
  
  
  TYPES = %i[
      by_category
      by_success_passing_on_the_first_try
      by_success_passing_all_tests_of_certain_level
    ].freeze

  def category
    @category ||= if rule_type == 'by_category'
      Category.find(rule_value)
    end
  end
  
  def test_level
    if rule_type == 'by_success_passing_all_tests_of_certain_level'
      rule_value
    end
  end
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show; end

  def new
    @badge = Badge.new
  end

  def edit; end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: 'Badge was successfully created.'
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badge_path, notice: 'Badge was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def set_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image, :rule_type, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def translate_types_from_symbol
    Badge::TYPES.map do |s|
      [t("admin.badges.types.#{s}"), s]
    end
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td><%= badge.title %></td>
  <td><%= image_tag(badge.image) %></td>
  <td>
    <%= t("admin.badges.types.#{badge.rule_type}") %>
    <% if badge.category %>
      <%= badge.category&.title %>
    <% end %>
    <% if badge.test_level %>
     <%= badge.test_level %>
    <% end %>
  </td>
  <td><%= link_to t('helpers.links.actions.show'), admin_badge_path(badge), :class => 'btn btn-primary' %></td>
  <td><%= link_to t('helpers.links.actions.edit'), edit_admin_badge_path(badge),:class => 'btn btn-success' %></td>
  <td>
    <%= link_to t('helpers.links.actions.delete'),
     admin_badge_path(badge),
     method: :delete,
     data: { confirm: t('helpers.links.actions.confirm') }, 
     :class => 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<div class="form-group m-3 ">
  <div class='row mb-5 mt-3'>
    <div class='col col-md-5'>
      <div class="card border-primary p-3">
        <%= form_with model: [:admin, badge], local: true do |form| %>
          <%= render 'shared/errors', resource: @badge %>

          <p>
            <%= form.label :title %>
            <%= form.text_field :title, class: 'form-control' %>
          </p>
          <p>
            <%= form.label :image %> 
            <%= form.text_field :image, class: 'form-control' %>
          </p>
  
          <p>
            <%= form.label :rule_type %>:
            <%= form.select :rule_type, translate_types_from_symbol, {prompt: true}, class: 'form-control selectSwitchFields' %>
          </p>
  
          
          <p>
            <%= form.label :rule_value %> 
            <%= form.number_field :rule_value, class: 'form-control' %>
          </p>
          
          <p><%= form.submit t( method_for_submit_form(@badge) ), class: 'btn btn-primary' %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Show', admin_badge_path(@badge) %> |
<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<div class="page-header m-3">
  <h1><%=t('.header') %></h1>
</div>

<%= render 'shared/errors', resource: @test %>

<table class="table table-striped m-3">
  <thead>
    <tr>
      <th><%= t(Badge.human_attribute_name(:title)) %></th>
      <th><%= t(Badge.human_attribute_name(:image)) %></th>
      <th><%= t(Badge.human_attribute_name(:type)) %></th>      
      <th colspan="3" scope="col" class="text-center"><%= t('.actions') %></th>
    </tr>
  </thead>
  <tbody >
    <%= render @badges %>
  </tbody>
</table>
<p>
  <%= link_to t('.new'), new_admin_badge_path, :class => 'btn btn-primary m-3' %>
</p>

app/views/admin/badges/new.html.erb
<h1>New Badge</h1>

<%= render 'form', badge: @badge %>

<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/show.html.erb
<div class="page-header m-3">
  <h2><%= t(Badge.model_name.human) %></h2>
</div>

<div class='container m-3'>
  <p>
    <b><%= t(Badge.human_attribute_name(:title)) %>:</b>
    <%= @badge.title %>
  </p>

  <p>
    <b><%= t(Badge.human_attribute_name(:image)) %>:</b>
    <%= image_tag(@badge.image) %>
  </p>
  
  <p>
    <b><%= t(Badge.human_attribute_name(:type)) %>:</b>
    <%= t("admin.badges.types.#{@badge.rule_type}") %> 
    <% if @badge.category %>
      <%= @badge.category&.title %>
    <% end %>
    <% if @badge.test_level %>
     <%= @badge.test_level %>
    <% end %>
  </p>
  



  <%= link_to t('admin.badges.show.back'), admin_badges_path, class: 'btn btn-primary' %>
</div>