config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :gists, only: :create

  resource :feedback, only: %i[new create]
  resources :badges, only: :index
  resources :received_badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passeges/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/admin.rb
class Admin < User
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true

  validate :validate_number

  scope :correct, -> { where(correct: true) }

  private

  def validate_number
    return unless new_record?

    errors.add(:number, 'too much answers') if Answer.where(question: question).count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord

  has_many :received_badge
  has_many :users, through: :received_badge
  
  
  TYPES = %i[
      by_category
      by_success_passing_on_the_first_try
      by_success_passing_all_tests_of_certain_level
    ].freeze

  def category
    @category ||= if rule_type == 'by_category'
      Category.find(rule_value)
    end
  end
  
  def test_level
    if rule_type == 'by_success_passing_all_tests_of_certain_level'
      rule_value
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(:title) }

  has_many :tests, dependent: :restrict_with_exception

  validates :title, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/passed_test.rb
class PassedTest < ApplicationRecord
  belongs_to :test
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, counter_cache: true

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :nullify, foreign_key: :current_question_id

  validates :body, presence: true

  def number
    test.questions.order(:id).where('id <= ?', id).count
  end
end

app/models/received_badge.rb
class ReceivedBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  belongs_to :author, class_name: 'User', inverse_of: :author_tests, optional: true

  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages

  has_many :questions, dependent: :destroy

  validates :title, presence: true,
                    uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than: 0 }

  scope :easy, -> { where(level: (0..1)) }
  scope :medium, -> { where(level: (2..4)) }
  scope :difficult, -> { where(level: (5..Float::INFINITY)) }

  scope :by_category, ->(category_name) { joins(:category).where(categories: { title: category_name }) }

  def self.titles_by_category(category_name)
    by_category(category_name).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  SUCCESS_RATIO = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def successful?
    counting_result >= SUCCESS_RATIO
  end

  def counting_result
    (correct_questions / test.questions.size.to_f) * 100
  end
  
  def timer_out?
    test.timer.present? && (created_at + test.timer*60 - Time.now) < 0
  end

  private

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first if current_question
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise  :database_authenticatable,
          :registerable,
          :recoverable,
          :rememberable,
          :validatable,
          :confirmable,
          :trackable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', inverse_of: :author, foreign_key: :author_id, dependent: :nullify
  has_many :received_badges, dependent: :destroy
  has_many :badges, through: :received_badges

  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: URI::MailTo::EMAIL_REGEXP, message: 'please enter email in correct format' }

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_test_passage

  def create
    result = GistQuestionService.new(@test_passage.current_question).call
    if result.success?
      Gist.create(
        user: current_user,
        question: @test_passage.current_question,
        url: result.html_url,
        gist_id: result.id
      )
      flash_options = { notice: t('.success_html', url: result.html_url) }
    else
      flash_options = { alert: t('.failure') }
    end

    redirect_to @test_passage, flash_options
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:test_passage_id])
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test, only: %i[start]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def set_test
    @test = Test.find(params[:id])
  end

  def rescue_with_test_not_found
    render plain: 'Test was not found'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_CLASS = {
    alert: 'danger',
    notice: 'info'
  }.freeze

  def current_year
    Date.current.year
  end

  def github_url(author, repo)
    link_to repo.to_s, "https://github.com/#{author}/#{repo}/", { target: '_blank', rel: 'nofollow' }
  end

  def flash_key_to_class(key)
    FLASH_CLASS[key.to_sym]
  end

  def method_for_submit_form(object)
    object.new_record? ? '.create' : '.update'
  end

  def progress_bar(max, current)
    content_tag(:div,
                content_tag(:div,
                            nil,
                            class: 'progress-bar',
                            data: {
                              max_value: max,
                              now_value: current
                            }),
                class: 'progress')
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def translate_types_from_symbol
    Badge::TYPES.map do |s|
      [t("admin.badges.types.#{s}"), s]
    end
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    title = question.test.title
    if question.new_record?
      t('admin.questions.create.header', title: title)
    else
      t('admin.questions.edit.header', title: title)
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/admin/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container">
  <span class="navbar-brand mb-0 h1">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to admin_badges_path, class: 'btn btn-primary ' do %>
    <%= octicon "file-badge", :height => 16 %>
  <% end %>
  <%= link_to t('.gist'), admin_gists_path, :class => 'btn btn-outline-success me-2' %>
</span>
  <span class="navbar-brand mb-0 h1"><%= t('admin.nav.header') %></span>

  <span class="navbar-text">
    <% if user_signed_in? %>
        <%= t('.welcome_html', email: current_user.email )%> | 
        <%= link_to t('.logout'), destroy_user_session_path, method: :delete %> 
      </p>
    <% else %>
      <%= link_to t('.login'), new_user_session_path %> | 
      <%= link_to t('.signup'), new_user_registration_path %>
    <% end %>
    </span>
  </div>
</nav>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
    <h2><%= t('.header', count: resource.errors.count) %>:</h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<%end%>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message.html_safe, class: ["alert alert-#{flash_key_to_class(key)}", "m-3"], role: "alert" %>
<% end %>

app/views/shared/_footer.html.erb
<div class="container m-3">
  <footer>
    <% if current_user %>
      <p>  
        <%= link_to t('.feedback'), new_feedback_path %>
      </p>
    <% end %>
    <%= current_year%><br>
    <%= t('.author_name') %><br>
    <%= github_url('lina1812', 'TestGuru') %><br>
    <%= t('.description')%><br>
    <%= link_to t('.link'), "https://thinknetica.com/", {target: "_blank", rel: "nofollow"} %>
  </footer>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container">
  <span class="navbar-brand mb-0 h1">
  <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>
  <%= link_to badges_path, class: 'btn btn-primary ' do %>
    <%= octicon "file-badge", :height => 16 %>
  <% end %>
  
  <% if current_user.is_a?(Admin) %>
    <%= link_to t('.admin_panel'), admin_tests_path, :class => 'btn btn-outline-success me-2' %>
  <% end %>
</span>
  <span class="navbar-text">
    <% if user_signed_in? %>
        <%= t('.welcome_html', email: current_user.email )%> | 
        <%= link_to t('.logout'), destroy_user_session_path, method: :delete %> 
    <% else %>
      <%= link_to t('.login'), new_user_session_path %> | 
      <%= link_to t('.signup'), new_user_registration_path %>
    <% end %>
  </span>
</div>
</nav>