config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: :gurus,
             path_names: { sign_in: :login, sign_out: :logout },
             controllers: { sessions: 'users/sessions' }

  get 'sessions/new'
  get 'users/new'

  root 'tests#index'

  resources :gists, only: :create

  resource :feedback, only: %i[new create]
  resources :badges, only: :index
  resources :received_badges, only: :index
  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passeges/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      get :finish
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
    resources :gists, only: :index
    resources :badges
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test, counter_cache: true

  has_many :answers, dependent: :destroy
  has_many :test_passages, dependent: :nullify, foreign_key: :current_question_id

  validates :body, presence: true

  def number
    test.questions.order(:id).where('id <= ?', id).count
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  SUCCESS_RATIO = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)
    save!
  end

  def completed?
    current_question.nil?
  end

  def successful?
    counting_result >= SUCCESS_RATIO
  end

  def counting_result
    (correct_questions / test.questions.size.to_f) * 100
  end
  
  def timer_out?
    test.timer.present? && (created_at + test.timer*60 - Time.now) < 0
  end

  private

  def correct_answer?(answer_ids)
    return false if answer_ids.nil?

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first if current_question
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_test_passage, only: %i[show update result finish]

  def show; end

  def result
    @counting_result = @test_passage.counting_result
  end

  def update
    if @test_passage.timer_out?
      redirect_to finish_test_passage_path(@test_passage) 
      return
    end

    @test_passage.accept!(params[:answer_ids])
    if @test_passage.completed?
      redirect_to finish_test_passage_path(@test_passage)
    else
      render :show
    end
  end
  
  def finish
    @test_passage.update(win: true) if @test_passage.successful?
    GettingBadgeService.new(@test_passage).call
    TestsMailer.completed_test(@test_passage).deliver_now
    redirect_to result_test_passage_path(@test_passage)
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<% if @test_passage.successful? %>
 <p class="succes">
  <%= t('.passed', result: @counting_result )%> 
 </p>
<% else %>
  <p class="fail">
     <%= t('.failed', result: @counting_result )%>
  </p>
<% end %>

<p>
<%= link_to t('helpers.links.navigation.back'), tests_path%>
</p>

app/views/test_passages/show.html.erb
<div class="page-header mt-3">
  <h1><%=t('.header', title: @test_passage.test.title) %></h1>
</div>
<% if @test_passage.test.timer.present? %>
  <h3><%=t('.time_left_html', time: (@test_passage.created_at + @test_passage.test.timer*60 - Time.now).ceil) %></h3>
<% end %>
<%= link_to 'finish', finish_test_passage_path(@test_passage), class: 'finish_link hide' %>
<div class='row mb-5 mt-3'>
  <div class='col col-md-5'>
    <div class="card border-primary p-3">
      <%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
        <legend>
          <%= @test_passage.current_question.body %>
          (<%= @test_passage.current_question.number %> / <%= @test_passage.test.questions.size %>)
        </legend>
        

    <%= progress_bar(@test_passage.test.questions.size, @test_passage.current_question.number) %>
  
        
        <div class="form-group mt-5">
          <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false do |b|%>
            <div class="form-check">
              <%= b.check_box id: "answer_ids_#{b.object.id}" %>
              <label class="form-check-label">
                <%= b.label %>
              </label>
            </div>
          <% end %>
        </div>
        <div class="form-group mt-3">
          <%= link_to t('.gist'), gists_path(test_passage_id: @test_passage.id), method: :post, class: 'btn btn-primary' %>
          <%= form.submit t('.next'), class: 'btn btn-success' %>
        </div>
      <% end %>
      
    </div>
  </div>
</div>